# -*- coding: utf-8 -*-
"""Pytest configuration and fixtures."""

import os
import subprocess

import pytest

from dnx.dns import Platform, get_platform


def _has_admin() -> bool:
    """Return True if the current process has admin/root privileges."""
    if get_platform() == Platform.WINDOWS:
        try:
            subprocess.check_call(
                ["net", "session"],
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
            )
            return True
        except (subprocess.CalledProcessError, FileNotFoundError):
            return False
    return os.geteuid() == 0


def pytest_configure(config):
    """Register custom markers."""
    config.addinivalue_line("markers", "linux: mark test to run only on Linux")
    config.addinivalue_line("markers", "windows: mark test to run only on Windows")
    config.addinivalue_line("markers", "macos: mark test to run only on macOS")
    config.addinivalue_line(
        "markers", "requires_admin: mark test that requires admin/root privileges"
    )


def pytest_collection_modifyitems(config, items):
    """Skip tests based on platform and privilege markers."""
    current = get_platform()
    admin = _has_admin()

    for item in items:
        if "linux" in item.keywords and current != Platform.LINUX:
            item.add_marker(pytest.mark.skip(reason="Test requires Linux"))
        elif "windows" in item.keywords and current != Platform.WINDOWS:
            item.add_marker(pytest.mark.skip(reason="Test requires Windows"))
        elif "macos" in item.keywords and current != Platform.MACOS:
            item.add_marker(pytest.mark.skip(reason="Test requires macOS"))

        if "requires_admin" in item.keywords and not admin:
            item.add_marker(
                pytest.mark.skip(reason="Test requires admin/root privileges")
            )


@pytest.fixture
def sample_resolv_conf(tmp_path):
    """Create a sample resolv.conf file."""
    content = """# Generated by NetworkManager
nameserver 192.168.1.1
nameserver 8.8.8.8
search local
"""
    resolv_file = tmp_path / "resolv.conf"
    resolv_file.write_text(content)
    return str(resolv_file)


@pytest.fixture
def sample_linux_route_output():
    """Sample output from 'ip route show default'."""
    return "default via 192.168.1.1 dev eth0 proto dhcp metric 100"


@pytest.fixture
def sample_macos_route_output():
    """Sample output from 'route -n get default' on macOS."""
    return """   route to: default
destination: default
       mask: default
    gateway: 192.168.1.1
  interface: en0
      flags: <UP,GATEWAY,DONE,STATIC,PRCLONING>
 recvpipe  sendpipe  ssthresh  rtt,msec    rttvar  hopcount      mtu     expire
       0         0         0         0         0         0      1500         0
"""


@pytest.fixture
def sample_macos_nwi_output():
    """Sample output from 'scutil --nwi' on macOS."""
    return """Network information

IPv4 network interface information
    en0 : flags      : 0x5 (IPv4,DNS)
          address    : 192.168.1.100
          reach      : 0x00000002 (Reachable)

   REACH : flags 0x00000002 (Reachable)

Network interfaces: en0
"""


@pytest.fixture
def sample_macos_hardware_ports():
    """Sample output from 'networksetup -listallhardwareports'."""
    return """Hardware Port: Wi-Fi
Device: en0
Ethernet Address: aa:bb:cc:dd:ee:ff

Hardware Port: Thunderbolt Ethernet
Device: en1
Ethernet Address: aa:bb:cc:dd:ee:00

"""


@pytest.fixture
def sample_windows_route_output():
    """Sample output from Windows Get-NetRoute PowerShell command."""
    return "Wi-Fi"


@pytest.fixture
def sample_windows_dns_output():
    """Sample output from Windows Get-DnsClientServerAddress."""
    return """8.8.8.8
8.8.4.4
"""


@pytest.fixture
def sample_ping_output_linux():
    """Sample ping output from Linux."""
    return """PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=118 time=12.3 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=118 time=11.8 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=118 time=12.1 ms

--- 8.8.8.8 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2003ms
rtt min/avg/max/mdev = 11.800/12.067/12.300/0.205 ms
"""


@pytest.fixture
def sample_ping_output_macos():
    """Sample ping output from macOS."""
    return """PING 8.8.8.8 (8.8.8.8): 56 data bytes
64 bytes from 8.8.8.8: icmp_seq=0 ttl=118 time=15.2 ms
64 bytes from 8.8.8.8: icmp_seq=1 ttl=118 time=14.8 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=118 time=15.0 ms

--- 8.8.8.8 ping statistics ---
3 packets transmitted, 3 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 14.800/15.000/15.200/0.163 ms
"""


@pytest.fixture
def sample_ping_output_windows():
    """Sample ping output from Windows."""
    return """
Pinging 8.8.8.8 with 32 bytes of data:
Reply from 8.8.8.8: bytes=32 time=12ms TTL=118
Reply from 8.8.8.8: bytes=32 time=11ms TTL=118
Reply from 8.8.8.8: bytes=32 time=13ms TTL=118

Ping statistics for 8.8.8.8:
    Packets: Sent = 3, Received = 3, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 11ms, Maximum = 13ms, Average = 12ms
"""


@pytest.fixture
def sample_ping_output_unreachable():
    """Sample ping output for unreachable host."""
    return """PING 10.255.255.1 (10.255.255.1) 56(84) bytes of data.

--- 10.255.255.1 ping statistics ---
3 packets transmitted, 0 received, 100% packet loss, time 2014ms
"""
