{% set name = "dnx" %}
{% set version = "0.1" %}

package:
    name: {{ name|lower }}
    version: {{ version }}
source:
    git_url: https://github.com/openscilab/dnx
    git_rev: v{{ version }}
build:
    noarch: python
    number: 0
    script: {{ PYTHON }} -m pip install . -vv
requirements:
    host:
        - pip
        - setuptools
        - python >=3.9
    run:
        - python >=3.9
about:
    home: https://github.com/openscilab/dnx
    license: MIT
    license_family: MIT
    summary: Minimal cross-platform DNS changer
    description: |
        dnx is a minimal cross-platform DNS changer CLI tool that supports
        Linux (systemd-resolved, NetworkManager, resolv.conf), Windows, and macOS.
extra:
    recipe-maintainers:
        - AHReccese
